actors:
  alice:
    image_url: /images/actors/mitsuhiko.jpg
    name: Mitsuhiko Yusa
    url: https://twitter.com/yusa1990
  bob:
    image_url: /images/actors/riku.jpg
    name: Riku Takenaka
    url: https://twitter.com/riijon
author: alice
description: この番組では、世の風流に敏感でハイセンス・ハイコンテクストな皆さまに、週ごとに担当する大将が、四季折々のささやかな小噺を提供するトークバラエティです。
description_long: この番組では、世の風流に敏感でハイセンス・ハイコンテクストな皆さまに、週ごとに担当する大将が、四季折々のささやかな小噺を提供するトークバラエティです。
email: riijon@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: otsumamitalk
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: おつまみトーク
url: https://otsumami-talk.github.io
